In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
acc_df = pd.read_csv('../acc_per_group.csv', decimal=',', delimiter=';')
acc_df["total count"] = acc_df["train count"] + acc_df["test count"]
acc_df = acc_df[acc_df["Run"] == 1]
acc_df[(acc_df["group"] == "mde-OM3-10") & (((acc_df["p"]==0.9) & (acc_df["gini"]==0.4))| (acc_df["Method"] == "RF+B"))]

,group,accuracy,train count,test count,samples per class,n_classes,Method,imbalance,p,gini,Run,target,equal,total count
74,mde-OM3-10,0.0,10,2,1.111111,9.0,SPH+CPI,very_high,0.9,0.4,1,NaN,NaN,12
102,mde-OM3-10,0.0,10,2,1.111111,9.0,CPI,very_high,0.9,0.4,1,NaN,NaN,12
1417,mde-OM3-10,NaN,2,2,NaN,NaN,RF+B,very_high,-1.0,-1.0,1,65.0,0.0,4
1567,mde-OM3-10,0.0,10,2,1.111111,9.0,SPH+CPI,high,0.9,0.4,1,NaN,NaN,12
1596,mde-OM3-10,0.0,10,2,1.111111,9.0,CPI,high,0.9,0.4,1,NaN,NaN,12
2962,mde-OM3-10,NaN,2,2,NaN,NaN,RF+B,high,-1.0,-1.0,1,65.0,0.0,4
4556,mde-OM3-10,0.0,11,1,1.222222,9.0,SPH+CPI,low,0.9,0.4,1,NaN,NaN,12
4584,mde-OM3-10,1.0,11,1,1.222222,9.0,CPI,low,0.9,0.4,1,NaN,NaN,12
5916,mde-OM3-10,NaN,3,1,NaN,NaN,RF+B,low,-1.0,-1.0,1,65.0,1.0,4
6064,mde-OM3-10,0.5,10,2,1.111111,9.0,SPH+CPI,very_low,0.9,0.4,1,NaN,NaN,12
7155,mde-OM3-10,NaN,2,2,NaN,NaN,RF+B,very_low,-1.0,-1.0,1,65.0,0.5,4

### SPH better than RF+B

In [73]:
pivot_df = pd.pivot_table(acc_df[acc_df["Method"] != "CPI"], values=["accuracy", "train count"], index=["group", "target"], columns="Method")

In [81]:
pivot_df = pd.pivot_table(acc_df[acc_df["Method"].isin( ["SPH", "RF+B"])], values=["accuracy", "total count"], index=["group"], columns="Method")
pivot_df[(pivot_df["accuracy"]["SPH"] > pivot_df["accuracy"]["RF+B"])]

            accuracy           total count
Method          RF+B       SPH        RF+B  SPH
group
hde-OM1-3   0.104167  0.166667    3.875000  3.0
hde-OM1-5   0.416667  0.500000    6.666667  3.0
hde-OM1-6   0.250000  0.666667    5.000000  8.0
hde-OM2-3   0.000000  0.500000    4.000000  3.0
hde-OM2-6   0.166667  0.500000    4.666667  3.0
hde-OM3-1   0.000000  0.666667    7.000000  3.0
hde-OM3-3   0.107143  0.333333    4.285714  3.0
mde-OM1-3   0.100000  0.473684    5.900000  4.0
mde-OM1-4   0.242857  0.391304    8.000000  3.0
mde-OM1-7   0.000000  1.000000    5.000000  5.0
mde-OM3-12  0.111111  0.625000    7.000000  3.0
mde-OM3-13  0.122024  0.440000   23.333333  6.0
mde-OM3-4   0.062500  0.117647    4.500000  5.0
mde-OM3-5   0.333333  0.714286    8.666667  4.0
mde-OM3-6   0.250000  0.571429    6.750000  3.0
mde-OM3-7   0.125000  0.333333    5.000000  3.0
mde-OM3-9   0.208333  0.428571    9.000000  3.0

In [82]:
pivot_df[(pivot_df["accuracy"]["SPH"]< pivot_df["accuracy"]["RF+B"])]

            accuracy           total count
Method          RF+B       SPH        RF+B  SPH
group
hde-OM2-1   0.153846  0.066667    3.461538  5.0
hde-OM2-5   0.111111  0.083333    3.333333  3.0
mde-OM1-2   0.375000  0.142857    5.250000  6.0
mde-OM3-11  0.333333  0.000000    7.000000  7.0

In [83]:
pivot_df = pd.pivot_table(acc_df[acc_df["Method"].isin( ["SPH", "RF+B"])], values=["accuracy", "total count"], index=["group"], columns="Method")
pivot_df[(pivot_df["accuracy"]["SPH"] > pivot_df["accuracy"]["RF+B"])]

            accuracy           total count
Method          RF+B       SPH        RF+B  SPH
group
hde-OM1-3   0.104167  0.166667    3.875000  3.0
hde-OM1-5   0.416667  0.500000    6.666667  3.0
hde-OM1-6   0.250000  0.666667    5.000000  8.0
hde-OM2-3   0.000000  0.500000    4.000000  3.0
hde-OM2-6   0.166667  0.500000    4.666667  3.0
hde-OM3-1   0.000000  0.666667    7.000000  3.0
hde-OM3-3   0.107143  0.333333    4.285714  3.0
mde-OM1-3   0.100000  0.473684    5.900000  4.0
mde-OM1-4   0.242857  0.391304    8.000000  3.0
mde-OM1-7   0.000000  1.000000    5.000000  5.0
mde-OM3-12  0.111111  0.625000    7.000000  3.0
mde-OM3-13  0.122024  0.440000   23.333333  6.0
mde-OM3-4   0.062500  0.117647    4.500000  5.0
mde-OM3-5   0.333333  0.714286    8.666667  4.0
mde-OM3-6   0.250000  0.571429    6.750000  3.0
mde-OM3-7   0.125000  0.333333    5.000000  3.0
mde-OM3-9   0.208333  0.428571    9.000000  3.0

In [58]:
pivot_df[(pivot_df["accuracy"]["SPH"] < pivot_df["accuracy"]["RF+B"])]

            accuracy
Method          RF+B       SPH
group
hde-OM2-1   0.244444  0.133333
mde-OM1-2   0.380952  0.190476
mde-OM1-4   0.437500  0.399554
mde-OM3-13  0.415689  0.411116

### SPH + CPI better than SPH

In [79]:
pivot_df = pd.pivot_table(acc_df[acc_df["Method"].isin(["SPH", "SPH+CPI"])], values=["accuracy", "total count"], index=["group", "target"], columns="Method")
pivot_df[pivot_df["accuracy"]["SPH"] < pivot_df["accuracy"]["SPH+CPI"]]

KeyError: 'accuracy'

In [80]:
pivot_df = pd.pivot_table(group_acc_df[group_acc_df["Method"].isin( ["SPH", "SPH+CPI"])], values=["accuracy", "total count"], index=["group"], columns="Method")

In [70]:
pivot_df

            accuracy
Method           SPH   SPH+CPI
group
hde-OM1-2   0.046154  0.050000
hde-OM1-3   0.173948  0.174541
hde-OM1-4   0.195266  0.211538
hde-OM1-5   0.490385  0.489583
hde-OM1-6   0.700000  0.700000
hde-OM2-1   0.103825  0.101190
hde-OM2-2   0.000000  0.000000
hde-OM2-3   0.715789  0.724138
hde-OM2-5   0.080247  0.073333
hde-OM2-6   0.664773  0.666667
hde-OM3-1   0.538462  0.527778
hde-OM3-3   0.487562  0.457885
mde-OM1-2   0.205128  0.190476
mde-OM1-3   0.546614  0.435384
mde-OM1-4   0.358322  0.354931
mde-OM1-5   0.000000  0.000000
mde-OM1-6   0.000000  0.000000
mde-OM1-7   0.915493  0.833333
mde-OM3-1   1.000000  0.000000
mde-OM3-11  0.538462  0.500000
mde-OM3-12  0.624542  0.648810
mde-OM3-13  0.403199  0.243449
mde-OM3-4   0.159722  0.161325
mde-OM3-5   0.660355  0.680769
mde-OM3-6   0.592593  0.580247
mde-OM3-7   0.432692  0.431250
mde-OM3-8   0.685897  0.687500
mde-OM3-9   0.553775  0.505401

In [37]:
acc_df[acc_df["Method"] == "SPH+CPI"].sort_values(["equal", "train count" ], ascending=[False, True])[0:21]

          group  target     equal  train count  test count   Method
1     hde-OM1-2       2  1.000000            2           1  SPH+CPI
14    hde-OM1-4      16  1.000000            3           1  SPH+CPI
57    mde-OM1-2      32  1.000000            3           1  SPH+CPI
34    hde-OM2-3      33  1.000000            4           1  SPH+CPI
82    mde-OM1-7      69  1.000000            4           1  SPH+CPI
83   mde-OM3-11      71  1.000000            4           3  SPH+CPI
18    hde-OM1-6      27  1.000000            5           2  SPH+CPI
28    hde-OM2-1       5  1.000000            5           1  SPH+CPI
15    hde-OM1-5      20  1.000000            6           4  SPH+CPI
46    hde-OM2-6      45  1.000000            7           2  SPH+CPI
84   mde-OM3-12      72  1.000000            7           3  SPH+CPI
114   mde-OM3-7      60  1.000000            7           2  SPH+CPI
51    hde-OM3-3      44  1.000000           10           4  SPH+CPI
110   mde-OM3-6      50  1.000000           12           4  SPH+CPI
108   mde-OM3-5      48  1.000000           13           5  SPH+CPI
60    mde-OM1-3      52  1.000000           24           9  SPH+CPI
120   mde-OM3-9      63  0.833333           14           6  SPH+CPI
99    mde-OM3-4      31  0.750000            6           4  SPH+CPI
71    mde-OM1-4      55  0.750000            9           4  SPH+CPI
95   mde-OM3-13      46  0.687500           31          16  SPH+CPI
48    hde-OM3-1      41  0.666667            4           3  SPH+CPI